# Generated by Django 6.0.6 on 2026-07-07 19:03

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [VectorExtension()]
